# Generated by Django 3.1.5 on 2021-06-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20210610_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=500)),
                ('send_by', models.IntegerField()),
                ('send_to', models.IntegerField()),
            ],
        ),
    ]
